// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmd0KyuXuqReTVbeGvRq6KRcaXQSzHh2M',
    appId: '1:1025437176913:web:cc08fa55496cc10a1ad470',
    messagingSenderId: '1025437176913',
    projectId: 'medicine-assistant-b2bce',
    authDomain: 'medicine-assistant-b2bce.firebaseapp.com',
    storageBucket: 'medicine-assistant-b2bce.firebasestorage.app',
    measurementId: 'G-3KJ4NZ26P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABM-wzLBcBteCuDHR_2zaPwBNpvbydEys',
    appId: '1:1025437176913:android:7d4a0c59bb93cc3a1ad470',
    messagingSenderId: '1025437176913',
    projectId: 'medicine-assistant-b2bce',
    storageBucket: 'medicine-assistant-b2bce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLBD-d-KtIP1l_9wsqVeJkZNAgpVwi2T4',
    appId: '1:1025437176913:ios:0c789f5493cf19571ad470',
    messagingSenderId: '1025437176913',
    projectId: 'medicine-assistant-b2bce',
    storageBucket: 'medicine-assistant-b2bce.firebasestorage.app',
    iosBundleId: 'com.example.medicineAssistant',
  );
}
